version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db  # Mantén este nombre
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: laboratorio
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-padmin"]
      interval: 5s
      timeout: 10s
      retries: 20

  app:
    build: .
    container_name: reto1_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/laboratorio?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: