spring.application.name=prueba-lis
server.servlet.context-path=/backend-lis/api

spring.datasource.url=jdbc:postgresql://localhost:5432/actividades-lis
spring.datasource.username=postgres
spring.datasource.password=utopia